---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/surveys/{survey_id}/answer_spreadsheet":
    parameters:
    - name: survey_id
      in: path
      description: survey's ID
      required: true
      schema:
        type: string
    - name: format
      in: query
      description: format of file (xlsx, csv, ods, xml, yaml)
      schema:
        type: string
    get:
      summary: show answer_spreadsheet
      responses:
        '200':
          description: sends file
        '400':
          description: incorrect format
        '404':
          description: survey not found
  "/surveys/{survey_id}/answer_statistics":
    parameters:
    - name: survey_id
      in: path
      description: survey_id
      required: true
      schema:
        type: string
    - name: date_from
      in: query
      description: from this date statistics will be collected
      schema:
        type: string
    - name: date_to
      in: query
      description: to this date statistics will be collected
      schema:
        type: string
    - name: except_question_numbers
      in: query
      description: numbers of questions, that are not included in statistics
      schema:
        type: string
    get:
      summary: show answer_statistic
      responses:
        '200':
          description: successful
        '404':
          description: not found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
